### ISSUE TITLE
Widen EDI Mapping Grid Columns

### ISSUE THREAD

**Issue by nmfujimoto** [meridianww/M4PLBase#318]
The Program EDI Mapping grid for Field Names need to be widen so the user can view the entire column text. 

There is an issue with the column header for the mapping records. If the user selects to change the width of the column the grid never releases the mouse click.

**Comment by nmfujimoto** [comment]
![image](https://user-images.githubusercontent.com/50392020/94497115-0e8ba400-01ab-11eb-81ec-1c7f89655941.png)

**Comment by prashantjustp** [comment]
Code fix has been deployed, Testing is pending.

**Comment by nmfujimoto** [comment]
@prashantjustp I am still seeing this problem in the Program module EDI screen. 
Expand AWC Customer node
Click on AWC Program node
Expand AWC204 Header row
Widen any of the AWC204 Detail columns, the column's width moves even when you release the cursor

![image](https://user-images.githubusercontent.com/50392020/95518213-785c3880-0977-11eb-9cb8-2ad13b6c6806.png)

**Comment by kirtya** [comment]
Feature has been developed and testing is in progress.
